### ISSUE TITLE
Mod overrides pose application

### ISSUE THREAD

**Issue by Sychic** [Walksy/ShieldFixes#6]
In [BipedEntityModelMixin](https://github.com/Walksy/ShieldFixes/blob/master/src/main/java/walksy/shield/mixin/BipedEntityModelMixin.java), despite [`setAngles`](https://github.com/Walksy/ShieldFixes/blob/master/src/main/java/walksy/shield/mixin/BipedEntityModelMixin.java#L80) not being marked as an `@Overwrite`, it still unconditionally cancels the original method. This creates compatibility issues with any other mods modifying the model's pose in that method and a more compatible way would be to use individual injections. One example is [Essential](https://essential.gg/)'s emotes.

Reproduction steps:
1. Add Shield Fixes
2. Add Essential
3. Join a world/server
4. Attempt to use an emote

Related: #4

**Comment by Walksy** [comment]
Done
